"""empty message

Revision ID: 51bcbb409d51
Revises: 28c86f40c0df
Create Date: 2023-10-02 23:01:13.341831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51bcbb409d51'
down_revision = '28c86f40c0df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('identity', schema=None) as batch_op:
        batch_op.alter_column('date_of_birth',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('identity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.VARCHAR(length=20), nullable=True))
        batch_op.alter_column('date_of_birth',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
